:stylesheet: ../../style.css

= Derivandi

**Source code analysis and generation at compile time**

Based on Annotation Processing, also called Annotation Processing Tool (APT).

Depending on your background, there are different guides:

- xref:Intro for new.adoc[new to metaprogramming]
- xref:Intro with meta.adoc[proficient in reflection or another metaprogramming API]
- xref:Intro with apt.adoc[proficient in annotation processing]


== When to use APT?

* The feedback cycle is as fast as possible. If generated sources are invalid the compiler will tell you
* It’s harder to make mistakes, as the compiler validates everything
* Meta Programming is always complex irespektve of the technology or api. Limiting it to compile time:
** Enforces separation of concerns with a hard boundary for architecture erosion
** Reasoning about an Annotation Processors impact on runtime is limited to the generated files and can therefore be drastically simpler
* No lock-in - generated sources can be added to the source tree and the generator removed

== When not to use APT?

* Annotation Processors are limited to compile time, if you need Meta Programming at runtime and generating behavioral patterns like Strategy is not enough
* Knowledge about the reflection is very common. Adding a new Technology increases the maintenance burden at least temporally

== Why this Library?

This project is easier to use and avoids common pitfalls of the Java APT API, It provides adapters so you’re not locked in and can easily work with other APT tooling.

Some key features are

- dependency free
- nulls save
- One Data Structure instead of two partially overlapping ones
- Types for Leafs of the abstract syntax tree, like Class, Enum or Method
- Java Source File DSL for easy generation
- Java Beans Support
- Generation of typesafe Annotation Representations

== Examples
.Builder Generator
[%collapsible]
====

[%linenums,java]
----
ifndef::site-gen-antora[]
include::../../../src/test/java/com/derivandi/builder/DerivandiBuilderProcessor.java[]
endif::[]
ifdef::site-gen-antora[]
include::example$builder/DerivandiBuilderProcessor.java[]
endif::[]
----
====

== Next Goals

* Add DSL support for method body contents
* More examples